/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AiOutlineGoogle } from "react-icons/ai";
import PricingSection from "@/components/PricingSection";


export function Bento() {
  return (
	<div className="py-4 px-2 mx-auto sm:py-4 lg:px-6">
		<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-4 h-full">
			<div className="col-span-2 sm:col-span-1 md:col-span-2 h-auto md:h-full flex flex-col">
                <div className=" bg-[#d7d7d5] rounded-2xl relative border border-stone-400/30">
                    <div className="grid gap-0 lg:grid-cols-2 xl:grid-cols-2">
                        <div className="md:pl-10 pb-4 content-center col-span-1 relative">
                            <h1 className="pb-6 text-stone-700 text-left font-extrabold tracking-tighter drop-shadow-sm [text-wrap:balance] text-4xl leading-[3rem] md:text-6xl md:leading-[3rem]">
                            The Ai Photographer
                            </h1>
                            <p className=" text-stone-500 md:text-xl">
                            Stunningly lifelike photos, as if taken by a professional photographer. 
                            </p> 
                            <div className="top-6 left-12 absolute w-32">
                                <span className="relative flex h-3 w-3 float-left mt-1 mr-2">
                                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                                <span className="relative inline-flex rounded-full h-3 w-3 bg-stone-400"></span>
                                </span>
                                <p className="text-stone-400 text-[12px]">Service is running</p>
                            </div>         
                        </div>
                        <div className="col-span-1 animate-fade-in animate-duration-[2s]">
                            <Image
                            className="cover rounded-2xl"
                            height="1168"
                            width="901"
                            alt="hello"
                            src="/v0.png"
                            />
                        </div>
                    </div>
                </div>
			</div>
			<div className="col-span-2 sm:col-span-1 md:col-span-2 bg-transparent">
				<a href="" className="h-64 group relative flex flex-col overflow-hidden rounded-2xl px-4 pb-4 pt-40 mb-4">
                    <Image src="/v1.jpg" 
                    width="1456"
                    height="832"
                    alt="" className="absolute inset-0 h-full w-full object-cover group-hover:scale-105 transition-transform duration-500 ease-in-out"></Image>
					
                    <div className="z-10 absolute top-6 left-6 w-full mx-auto text-center">
                        <h3 className="text-stone-300 font-thin tracking-tight drop-shadow-xl [text-wrap:balance] text-4xl leading-[3rem] md:text-4xl md:leading-[3rem]">
                            Upload your photos<br/>& <span className="font-bold">create your Ai twin!</span>
                        </h3>
                    </div>
                        
                    <div className="w-82 mb-6 flex flex-row gap-1 mx-auto relative">
                        <Image
                            className="cover w-14 h-14 rounded-full ml-4 shadow-md border shadow-stone-800/20"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s1.png"
                        />
                        <Image
                            className="cover w-14 h-14 rounded-full -ml-4 shadow-md border shadow-stone-800/20"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s2.png"
                        />
                        <Image
                            className="cover w-14 h-14 rounded-full -ml-4 shadow-md border shadow-stone-800/20"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s3.png"
                        />
                        <Image
                            className="cover w-14 h-14 rounded-full -ml-4 shadow-md border shadow-stone-800/20"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s4.png"
                        />
                        
                        <div className="w-14 h-14 z-40 transition-all ml-1">
                            <div className="cursor-pointer pt-[11px] pl-[11px] z-40  transition-all  text-center text-4xl font-bold tracking-tighter w-14 h-14 rounded-full border border-stone-100 bg-gradient-to-b from-stone-250 to-white shadow-xl shadow-stone-950/90">
                            <PlusIcon/>
                            </div>
                        </div>
                        
                    </div>
				</a>
				<div className="">
                    <PricingSection/>
				</div>
			</div>
			<div className="col-span-2 sm:col-span-1 md:col-span-1 bg-sky-50 h-auto md:h-full flex flex-col rounded-2xl">
				<a href="" className="group relative flex flex-col overflow-hidden rounded-2xl px-4 pb-4 pt-40 flex-grow">
                    <Image src="/v1.jpg" 
                    width="2940"
                    height="1960"
                    alt="" className="absolute inset-0 h-full w-full object-cover group-hover:scale-105 transition-transform duration-500 ease-in-out"></Image>
					<div className="absolute inset-0 bg-gradient-to-b from-gray-900/25 to-gray-900/5"></div>
					<h3 className="z-10 text-2xl font-medium text-white absolute top-0 left-0 p-4 xs:text-xl md:text-3xl">Brandy</h3>
				</a>
			</div>
		</div>

	</div>
  )
}



function RocketIcon() {
    return (
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6">
        <path fill-rule="evenodd" d="M9.315 7.584C12.195 3.883 16.695 1.5 21.75 1.5a.75.75 0 0 1 .75.75c0 5.056-2.383 9.555-6.084 12.436A6.75 6.75 0 0 1 9.75 22.5a.75.75 0 0 1-.75-.75v-4.131A15.838 15.838 0 0 1 6.382 15H2.25a.75.75 0 0 1-.75-.75 6.75 6.75 0 0 1 7.815-6.666ZM15 6.75a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5Z" clip-rule="evenodd" />
        <path d="M5.26 17.242a.75.75 0 1 0-.897-1.203 5.243 5.243 0 0 0-2.05 5.022.75.75 0 0 0 .625.627 5.243 5.243 0 0 0 5.022-2.051.75.75 0 1 0-1.202-.897 3.744 3.744 0 0 1-3.008 1.51c0-1.23.592-2.323 1.51-3.008Z" />
      </svg>
      
    )
  }

  export function PlusIcon() {
    return (
        <svg className="w-8 h-8" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.9 0.499976C13.9 0.279062 13.7209 0.0999756 13.5 0.0999756C13.2791 0.0999756 13.1 0.279062 13.1 0.499976V1.09998H12.5C12.2791 1.09998 12.1 1.27906 12.1 1.49998C12.1 1.72089 12.2791 1.89998 12.5 1.89998H13.1V2.49998C13.1 2.72089 13.2791 2.89998 13.5 2.89998C13.7209 2.89998 13.9 2.72089 13.9 2.49998V1.89998H14.5C14.7209 1.89998 14.9 1.72089 14.9 1.49998C14.9 1.27906 14.7209 1.09998 14.5 1.09998H13.9V0.499976ZM11.8536 3.14642C12.0488 3.34168 12.0488 3.65826 11.8536 3.85353L10.8536 4.85353C10.6583 5.04879 10.3417 5.04879 10.1465 4.85353C9.9512 4.65827 9.9512 4.34169 10.1465 4.14642L11.1464 3.14643C11.3417 2.95116 11.6583 2.95116 11.8536 3.14642ZM9.85357 5.14642C10.0488 5.34168 10.0488 5.65827 9.85357 5.85353L2.85355 12.8535C2.65829 13.0488 2.34171 13.0488 2.14645 12.8535C1.95118 12.6583 1.95118 12.3417 2.14645 12.1464L9.14646 5.14642C9.34172 4.95116 9.65831 4.95116 9.85357 5.14642ZM13.5 5.09998C13.7209 5.09998 13.9 5.27906 13.9 5.49998V6.09998H14.5C14.7209 6.09998 14.9 6.27906 14.9 6.49998C14.9 6.72089 14.7209 6.89998 14.5 6.89998H13.9V7.49998C13.9 7.72089 13.7209 7.89998 13.5 7.89998C13.2791 7.89998 13.1 7.72089 13.1 7.49998V6.89998H12.5C12.2791 6.89998 12.1 6.72089 12.1 6.49998C12.1 6.27906 12.2791 6.09998 12.5 6.09998H13.1V5.49998C13.1 5.27906 13.2791 5.09998 13.5 5.09998ZM8.90002 0.499976C8.90002 0.279062 8.72093 0.0999756 8.50002 0.0999756C8.2791 0.0999756 8.10002 0.279062 8.10002 0.499976V1.09998H7.50002C7.2791 1.09998 7.10002 1.27906 7.10002 1.49998C7.10002 1.72089 7.2791 1.89998 7.50002 1.89998H8.10002V2.49998C8.10002 2.72089 8.2791 2.89998 8.50002 2.89998C8.72093 2.89998 8.90002 2.72089 8.90002 2.49998V1.89998H9.50002C9.72093 1.89998 9.90002 1.72089 9.90002 1.49998C9.90002 1.27906 9.72093 1.09998 9.50002 1.09998H8.90002V0.499976Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
    )
}


